#!/usr/bin/env bash
# Manages 'manage_my_process'

if [ "${1}" == "start" ]
then
    sudo bash ./manage_my_process
    touch /var/run/my_process.pid
    MYPID="$(pgrep -f manage_my_process)"
    bash -c 'echo $MYPID > /var/run/my_process.pid'
    echo "manage_my_process started"
elif [ "${1}" == "stop" ]
then
    pkill -f manage_my_process
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
elif [ "${1}" == "restart" ]
then
    pkill -f manage_my_process
    rm /var/run/my_process.pid
    sudo bash ./manage_my_process
    touch /var/run/my_process.pid
    MYPID="$(pgrep -f manage_my_process)"
    bash -c 'echo $MYPID > /var/run/my_process.pid'
    echo "manage_my_process restarted"
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
