#!/usr/bin/env bash
# displays Holberton School 10 times.

COUNTER=1
while [ $COUNTER -lt 11 ]
do
    if [ $COUNTER = 4 ]
    then
        echo "bad luck"
    elif [ $COUNTER = 8 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
    let COUNTER+=1
done
